### ISSUE TITLE
活动邀请函 图片生成器

### ISSUE THREAD

**Issue by TechQuery** [Open-Source-Bazaar/Open-Source-Bazaar.github.io#4]
## 设计效果

![mmexport1645470740247.jpg](https://user-images.githubusercontent.com/19969570/155014589-3307d916-41a2-4843-86f0-3e890d39e505.jpg)

切图问设计师花花

## 程序架构

纯前端 输入文字、上传图片、Canvas 截图、文件保存

**Comment by stevending1st** [comment]
相关讨论迁移至 https://github.com/Open-Source-Bazaar/osb-poster/issues/2
